[package]
name = "midi_synth"
version = "0.1.0"
authors = ["Ryan McCampbell <rmccampbell7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
cpal = "0.18"
ctrlc = "3.5"
midir = "0.11"
midly = "0.5"
