[package]
name = "midi_synth"
version = "0.1.0"
authors = ["Ryan McCampbell <rmccampbell7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
cpal = "0.16.0"
ctrlc = "3.5.0"
midir = "0.10.2"
wmidi = "4.0.10"
