[package]
name = "midi_synth"
version = "0.1.0"
authors = ["Ryan McCampbell <rmccampbell7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
clap = "2.33.3"
cpal = "0.13.4"
ctrlc = "3.2.0"
midir = "0.7.0"
structopt = "0.3.23"
thiserror = "1.0.28"
wmidi = "4.0.6"
